### ISSUE TITLE
Junimo Huts in Grampleton Fields [and other additional farms with huts]

### ISSUE THREAD

**Issue by TheSilentE** [hawkfalcon/Stardew-Mods#34]
The SVE Grampleton Fields addon allows you to have build junimo huts in a fairly expansive extra farming map, but Better Junimos seems not to have an effect on huts built there, and I got a fairly lengthy error message when I did build one.

SMAPI LOG: [https://smapi.io/log/637fb89ec88a4af98cd3d07719cb10ee](https://smapi.io/log/637fb89ec88a4af98cd3d07719cb10ee)

**Comment by hawkfalcon** [comment]
Hmm, it currently explicitly only works on 'the farm'. Not sure how to make it work for other locations.

**Comment by hawkfalcon** [comment]
This might fix it, untested https://github.com/hawkfalcon/Stardew-Mods/releases/tag/3.0.1-beta

**Comment by goingcrazy1st** [comment]
I just tried this with the Buildable Ginger Island Farm and no junimos at all, not even just harvesting. When I tried to spawn a junimo, I got the message saying they can only spawn on the farm or greenhouse. I have not tried the flower harvesting since I don't currently have any flowers planted. Thanks for trying. Here's the log: https://smapi.io/log/d34c1155633647c5aefed21d30f7a205
